### ISSUE TITLE
[Umbrella] Submit task 25 to metriq with different versions of Qiskit

### ISSUE THREAD

**Issue by 1ucian0** [qiskit-community/submit-metriq#1]
The [task 25](https://metriq.info/Task/25) takes the circuit depth and the gate count of the result of compiling this QASM2 into 
 Rigetti 16Q Aspen-1 and ibmq-rochester

```
OPENQASM 2.0;
include "qelib1.inc";
qreg q[16];
creg c[16];
cx q[3],q[0];
cx q[1],q[0];
cx q[5],q[0];
x q[2];
cx q[2],q[0];
x q[4];
cx q[4],q[0];
```

- [x] Create tox env with different versions of Qiskit
- [x] Run 100 tranpilation in each of them
- [x] Submit the average and stddev to metriq

**Comment by 1ucian0** [comment]
Where is a first quick draft:

```
qasm_in = """
OPENQASM 2.0;
include "qelib1.inc";
qreg q[16];
creg c[16];
cx q[3],q[0];
cx q[1],q[0];
cx q[5],q[0];
x q[2];
cx q[2],q[0];
x q[4];
cx q[4],q[0];
"""

from qiskit import QuantumCircuit
circuit = QuantumCircuit.from_qasm_str(qasm_in)

# transpile for 
from qiskit.providers.fake_provider import FakeRochesterV2
from qiskit import transpile

backend = FakeRochesterV2()
for optlevel in range(0, 4):
    result = transpile(circuit, backend=FakeRochesterV2(), optimization_level=optlevel)
    print(backend.backend_name, optlevel)
    print(result.depth())
    print(sum(result.count_ops().values()))
```

**Comment by 1ucian0** [comment]
Using pyzx (which I assume what researchers did in Task 25), looks like this
```python
qasm_in = """
OPENQASM 2.0;
include "qelib1.inc";
qreg q[16];
creg c[16];
cx q[3],q[0];
cx q[1],q[0];
cx q[5],q[0];
x q[2];
cx q[2],q[0];
x q[4];
cx q[4],q[0];
"""
from qiskit import QuantumCircuit
from qiskit.transpiler import CouplingMap
from pyzx.routing import create_architecture

circuit = QuantumCircuit.from_qasm_str(qasm_in)

# transpile for each architecture
for arch in ['ibm_rochester', 'rigetti_16q_aspen']:
    architecture = create_architecture(arch)
    coupling_map = CouplingMap(architecture.graph.edges())

    # transpile 
    from qiskit import transpile
    result = transpile(circuit, coupling_map=coupling_map, optimization_level=3)
    print(architecture.name, result.depth(), sum(result.count_ops().values()))
```
```
ibm_rochester 9 13
rigetti_16q_aspen 10 16
```

**Comment by karlaspuldaro** [comment]
@1ucian0 I had to add `from pyzx import routing` to the code above and call `routing.create_architecture(arch)` instead, in order to run it locally.

Going to create separate issues/PRs for the main tasks.

**Comment by 1ucian0** [comment]
oh! I forgot `from pyzx.routing import create_architecture` indeed.

**Comment by WrathfulSpatula** [comment]
Hey, by the way, this is Dan, of the Metriq web app project! If I can help in any way, including with development on the Metriq end, I'm here!

**Comment by vprusso** [comment]
Chiming in here as well along with @WrathfulSpatula . If we can help out regarding the Metriq project, do let us know!
